### ISSUE TITLE
Adding connection to DIY sensors

### ISSUE THREAD

**Issue by petrk94** [Tanibox/tania#40]
Hello,
I really like the interface, but I would like to know whether it were possible to create a connector of it to sensor websites or a connector to arduino with a mesh of farm sensors which sending information via MQTT, etc.

Thanks

**Comment by bepitulaz** [comment]
Hello,
For the current version 1.0.1 and the next 1.1 (we will release it very soon), it is not possible. But we have the plan to receive the data from the DIY sensor because we also use some sensors that attach to RPi and ESP8266 in our garden that we would like to connect it to Tania. We will put the feature to our development roadmap.

Anyway, how do you use sensors at your farm? Do you connect it directly from Arduino to the server or are you using gateway before sending the data to the server? I mean like Arduino -> RPi -> server.

Thanks.

**Comment by petrk94** [comment]
@bepitulaz 
Hello, thanks for the answer.
I dont own a farm, Im a web developer/admin/etc.^^
Im looking for a solution which I can offer farmers, because they want all from one hand and not invest so much money, due, at least in Germany, they doesnt earn so much.
For the sensor connection I would think a arduino and ESP8266 or BLE, due ESP8266 need alot power and sensors should be working autonomous for a longer time.
A Raspberry Pi would be the server host in this case.

**Comment by bepitulaz** [comment]
Hi @petrk94,
If you don't mind, may I discuss with you via an email? Since you said about Germany, I have a few questions to ask. My email is asep@tanibox.com.

Thanks.

_Sent from my Lenovo K33a42 using [FastHub](https://play.google.com/store/apps/details?id=com.fastaccess.github)_

**Comment by petrk94** [comment]
@bepitulaz send you email

**Comment by bepitulaz** [comment]
@petrk94 I replied it. So, we can close this issue for now.
